In [1]:
!pip install numpy

In [2]:
import numpy as np

1. Create

In [33]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [34]:
data

array([[[0.98765636, 0.61523035, 0.11296224, 0.79325054],
        [0.99051064, 0.79373952, 0.07427699, 0.60168129],
        [0.55169499, 0.25279147, 0.01986875, 0.90345722]],

       [[0.94851636, 0.52199593, 0.64285886, 0.78449524],
        [0.9932294 , 0.71803749, 0.84785266, 0.42757193],
        [0.82169345, 0.09850568, 0.41322346, 0.50508939]]])

In [35]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [36]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [37]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [38]:
type(arr)

numpy.ndarray

2. Read

In [39]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [40]:
types

dtype('float64')

In [41]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [42]:
slicer

array([[0.98765636, 0.61523035, 0.11296224, 0.79325054],
       [0.99051064, 0.79373952, 0.07427699, 0.60168129]])

In [43]:
data

array([[[0.98765636, 0.61523035, 0.11296224, 0.79325054],
        [0.99051064, 0.79373952, 0.07427699, 0.60168129],
        [0.55169499, 0.25279147, 0.01986875, 0.90345722]],

       [[0.94851636, 0.52199593, 0.64285886, 0.78449524],
        [0.9932294 , 0.71803749, 0.84785266, 0.42757193],
        [0.82169345, 0.09850568, 0.41322346, 0.50508939]]])

3. Update

In [44]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [45]:
list1

array([0.34680807, 0.36392155, 0.74619082, 0.60114674, 0.78597987,
       0.01306287, 0.19218111, 0.97980044, 0.56166773, 0.83310374])

In [46]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [47]:
add

array([0.89716364, 0.66302606, 0.79387255, 0.68567103, 1.5814667 ,
       0.10955996, 0.21450994, 1.0973573 , 0.9733658 , 1.25346816])

In [48]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [49]:
# SAPLEMM

In [50]:
data[0][0][0] = 700

In [51]:
data

array([[[7.00000000e+02, 6.15230350e-01, 1.12962236e-01, 7.93250542e-01],
        [9.90510644e-01, 7.93739523e-01, 7.42769904e-02, 6.01681288e-01],
        [5.51694991e-01, 2.52791470e-01, 1.98687476e-02, 9.03457217e-01]],

       [[9.48516359e-01, 5.21995932e-01, 6.42858860e-01, 7.84495235e-01],
        [9.93229396e-01, 7.18037489e-01, 8.47852658e-01, 4.27571925e-01],
        [8.21693454e-01, 9.85056760e-02, 4.13223461e-01, 5.05089395e-01]]])

In [52]:
data.sort()
data

array([[[1.12962236e-01, 6.15230350e-01, 7.93250542e-01, 7.00000000e+02],
        [7.42769904e-02, 6.01681288e-01, 7.93739523e-01, 9.90510644e-01],
        [1.98687476e-02, 2.52791470e-01, 5.51694991e-01, 9.03457217e-01]],

       [[5.21995932e-01, 6.42858860e-01, 7.84495235e-01, 9.48516359e-01],
        [4.27571925e-01, 7.18037489e-01, 8.47852658e-01, 9.93229396e-01],
        [9.85056760e-02, 4.13223461e-01, 5.05089395e-01, 8.21693454e-01]]])

In [53]:
print(data.shape)

(2, 3, 4)


In [54]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [56]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [57]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


4. Delete

In [58]:
data

array([[[1.12962236e-01, 6.15230350e-01, 7.93250542e-01, 7.00000000e+02,
         7.42769904e-02, 6.01681288e-01],
        [7.93739523e-01, 9.90510644e-01, 1.98687476e-02, 2.52791470e-01,
         5.51694991e-01, 9.03457217e-01]],

       [[5.21995932e-01, 6.42858860e-01, 7.84495235e-01, 9.48516359e-01,
         4.27571925e-01, 7.18037489e-01],
        [8.47852658e-01, 9.93229396e-01, 9.85056760e-02, 4.13223461e-01,
         5.05089395e-01, 8.21693454e-01]]])

In [59]:
np.delete(data, 0, axis=1)

array([[[0.79373952, 0.99051064, 0.01986875, 0.25279147, 0.55169499,
         0.90345722]],

       [[0.84785266, 0.9932294 , 0.09850568, 0.41322346, 0.50508939,
         0.82169345]]])

In [61]:
print(data.shape)

(2, 2, 6)


In [62]:
np.save("new array", data)

In [63]:
test = np.load("new array.npy")
print(test)

[[[1.12962236e-01 6.15230350e-01 7.93250542e-01 7.00000000e+02
   7.42769904e-02 6.01681288e-01]
  [7.93739523e-01 9.90510644e-01 1.98687476e-02 2.52791470e-01
   5.51694991e-01 9.03457217e-01]]

 [[5.21995932e-01 6.42858860e-01 7.84495235e-01 9.48516359e-01
   4.27571925e-01 7.18037489e-01]
  [8.47852658e-01 9.93229396e-01 9.85056760e-02 4.13223461e-01
   5.05089395e-01 8.21693454e-01]]]
